import { Download, Search } from 'lucide-react'
import type { FormEvent } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { boxKeys, type Box, type Query } from '@/types'

type Props = { box: Box; blob: Blob | null; busy: boolean; hasResult: boolean; mode: 'ranking' | 'candidates'; queryFilter: string; selectedQuery: string; threshold: string; topK: number; visibleQueries: Query[]; onBoxChange: (key: keyof Box, value: string) => void; onDownload: () => void; onModeChange: (value: 'ranking' | 'candidates') => void; onQueryFilterChange: (value: string) => void; onSelectFile: (file?: File) => Promise<void>; onSelectQuery: (id: string) => Promise<void>; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onThresholdChange: (value: string) => void; onTopKChange: (value: number) => void }

export function SearchForm(p: Props) {
  return <Card className="bg-white/[.04] text-white ring-white/15"><CardHeader><CardTitle className="text-xs tracking-[.12em] uppercase">01 / Параметры поиска</CardTitle><CardDescription>Источник, BBox и режим.</CardDescription></CardHeader><CardContent><form className="space-y-5" onSubmit={p.onSubmit}>
    <label className="grid gap-2 text-[10px] tracking-[.1em] text-white/55 uppercase">Файл JPEG или PNG<input className="h-10 border border-white/15 bg-black px-3 text-xs" type="file" accept="image/jpeg,image/png" onChange={(e) => void p.onSelectFile(e.target.files?.[0])} /></label>
    <div className="grid gap-2"><label className="text-[10px] tracking-[.1em] text-white/55 uppercase" htmlFor="query-filter">Официальный query</label><input id="query-filter" className="h-10 border border-white/15 bg-black px-3 text-xs" placeholder="Введите часть ID" value={p.queryFilter} onChange={(e) => p.onQueryFilterChange(e.target.value)} /><div className="max-h-36 overflow-y-auto border border-white/10 bg-black">{p.visibleQueries.map((query) => <button data-testid="query-option" className={`block w-full border-b border-white/10 px-3 py-2 text-left text-xs break-all hover:bg-white/10 ${p.selectedQuery === query.image_id ? 'bg-white text-black hover:bg-white' : ''}`} key={query.image_id} type="button" onClick={() => void p.onSelectQuery(query.image_id)}>{query.image_id}</button>)}{!p.visibleQueries.length && <p className="px-3 py-2 text-xs text-white/45">Совпадений не найдено</p>}</div><p className="text-[10px] leading-4 text-white/45">Показано до 8 совпадений. Выбор подставляет BBox из официального CSV.</p></div>
    <div className="border-t border-white/15 pt-5"><p className="mb-3 text-[10px] tracking-[.12em] text-white/55 uppercase">02 / Граница автомобиля</p><div className="grid grid-cols-2 gap-3">{boxKeys.map((key) => <label key={key} className="grid gap-2 text-[10px] tracking-[.1em] text-white/55 uppercase">{key}<input className="h-10 border border-white/15 bg-black px-3 text-xs" type="number" min="0" value={p.box[key] || ''} onChange={(e) => p.onBoxChange(key, e.target.value)} /></label>)}</div></div>
    <div className="border-t border-white/15 pt-5"><p className="mb-3 text-[10px] tracking-[.12em] text-white/55 uppercase">03 / Режим</p><label className="grid gap-2 text-[10px] tracking-[.1em] text-white/55 uppercase">Количество результатов<input className="h-10 border border-white/15 bg-black px-3 text-xs" type="number" min="1" max="100" value={p.topK} onChange={(e) => p.onTopKChange(Number(e.target.value))} /></label><label className="mt-3 grid gap-2 text-[10px] tracking-[.1em] text-white/55 uppercase">Режим<select className="h-10 border border-white/15 bg-black px-3 text-xs" value={p.mode} onChange={(e) => p.onModeChange(e.target.value as 'ranking' | 'candidates')}><option value="ranking">Ранжирование</option><option value="candidates">Кандидаты с отказом</option></select></label><label className="mt-3 grid gap-2 text-[10px] tracking-[.1em] text-white/55 uppercase">Порог cosine<input className="h-10 border border-white/15 bg-black px-3 text-xs" type="number" min="-1" max="1" step="any" value={p.threshold} placeholder="Автоматически" onChange={(e) => p.onThresholdChange(e.target.value)} /></label></div>
    <Button className="w-full rounded-none" disabled={!p.blob || p.busy} type="submit"><Search />{p.busy ? 'Поиск…' : 'Запустить поиск'}</Button><Button className="w-full rounded-none" variant="outline" disabled={!p.hasResult} type="button" onClick={p.onDownload}><Download />Скачать JSON</Button>
  </form></CardContent></Card>
}
